### ISSUE TITLE
This broke my kali

### ISSUE THREAD

**Issue by Sheikh-Nightshader** [mishakorzik/Free-Proxy#8]
this broke my kali i had to reinstall it. This package installed not free proxy but a bunch of other things other than what was said

**Comment by ghost** [comment]
Hi, it seems that this project is no longer being maintained. I've made a fork of FreeProxy called FreeProxyX which is updated to python 3.11 and with new features. Try it out if you want [https://github.com/noahdossan/Free-ProxyX](https://github.com/noahdossan/Free-ProxyX) feedback would be appreciated.

For now I had to disable the update scripts because it seemed like the update scripts were installing a bunch of other things like you said

**Comment by ghost** [comment]
I'm also working on updating the proxies list as all of the proxies I've gotten from the proxy scraper are dead.

**Comment by mishakorzik** [comment]
> this broke my kali i had to reinstall it. This package installed not free proxy but a bunch of other things other than what was said

Hi, it cannot break your kali. Maybe your incorrect install?

**Comment by Sheikh-Nightshader** [comment]
I thought it was going to install just this proxy scanner thing but it installed kali instead. It should of only installed the proxy tool but my system tried to install kali again on itself. I had to redo everything. Tho i do like your other works and thank you for those but. That happened.

**Comment by mishakorzik** [comment]
I checked and it can't install Kali. It installs only Free-Proxy.

**Comment by Sheikh-Nightshader** [comment]
Thats strange because it did it to me. I am using nethunter kali on the device i did this on
